name: Region
version: '${project.version}'
main: win.oreo.region.Main
authors: [ superoreo ]
description: Region Plugin
website: https://github.com/superoreoooooo
commands:
  region:
    aliases:
      - 지역
      - reg